Prevent health check from failing start and stop workflow
Set health check outcome in outputs so that early termination won't cause entire workflow to fail

diff --git a/.github/workflows/start_url_shortener.yml b/.github/workflows/start_url_shortener.yml
--- a/.github/workflows/start_url_shortener.yml
+++ b/.github/workflows/start_url_shortener.yml
@@ -17,15 +17,26 @@ on:
 jobs:
   health_check:
     runs-on: ubuntu-latest
+    continue-on-error: true
+    outputs:
+      health_check_outcome: ${{ steps.health_check.outputs.outcome }}
     env:
       URL_SHORTENER_HOST_NAME: ${{ secrets.URL_SHORTENER_HOST_NAME }}
     steps:
       - name: Check if URL shortener is already running
+        id: health_check
         run: |
-          curl $URL_SHORTENER_HOST_NAME/healthz
+          health_check=$(curl $URL_SHORTENER_HOST_NAME/healthz || true)
+          if [ -n "$health_check" ]
+          then
+            echo "::set-output name=outcome::success"
+          else
+            echo "::set-output name=outcome::failure"
+          fi
   notify_already_running:
     runs-on: ubuntu-latest
     needs: [health_check]
+    if: ${{ needs.health_check.outputs.health_check_outcome == 'success' }}
     steps:
       - name: Send slack notification URL shortener is already running
         env:
@@ -38,7 +49,7 @@ jobs:
   start_ec2_and_deploy:
     runs-on: ubuntu-latest
     needs: [health_check]
-    if: ${{ failure() }}
+    if: ${{ needs.health_check.outputs.health_check_outcome == 'failure' }}
     env:
       DOMAIN: ${{ secrets.DOMAIN }}
       URL_REDIRECT_DOMAIN: ${{ secrets.URL_REDIRECT_DOMAIN }}
@@ -56,8 +67,6 @@ jobs:
           ls -la
 
           # Install ansible and required dependencie          
-          # sudo apt-get update
-          # sudo apt-get -y install ansible python3-botocore python3-boto3
           python3 -m pip install ansible boto3
           
           python3 --version
@@ -159,6 +168,7 @@ jobs:
   notify_successful:
     runs-on: ubuntu-latest
     needs: [start_ec2_and_deploy]
+    if: ${{ always() && needs.start_ec2_and_deploy.result == 'success' }}
     steps:
       - name: Send slack notification successful run
         env:
